name: EPL Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |

          sudo apt-get update

          sudo apt-get install -y \
            wget \
            curl \
            unzip \
            xvfb \
            libxi6 \
            libgconf-2-4 \
            default-jdk \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libasound2t64

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install undetected-chromedriver
          pip install selenium
          pip install beautifulsoup4
          pip install lxml

      - name: Verify Chrome
        run: |
          google-chrome --version

      - name: Run EPL Scraper
        run: |
          xvfb-run python scripts/epl_scraper.py

      - name: Commit EPL Updates
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/data/epl

          git commit -m "Update EPL data" || echo "No changes"

          git pull --rebase origin main || true

          git push
