name: MLB Live Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install requests

      - name: Run scraper
        run: |
          python scripts/mlb_live_builder.py

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/baseball/boxscores/2026/
          git commit -m "Update MLB live games" || echo "No changes"
          git push
