name: NBA Full Rebuild

on:
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests

      - name: Run NBA rebuild
        run: |
          python scripts/nba_full_rebuild.py

      - name: Commit rebuilt NBA files
        run: |

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          echo "CHECKING FILES"

          ls docs/data/nba/boxscores/2026 | head

          git add -A docs/data/nba

          git status

          git commit -m "Restore NBA boxscores" || echo "No changes"

          git push
