name: nba

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install python packages
        run: pip install requests pandas

      - name: run updater
        run: python scripts/update_recent_nba_games.py
