name: NFL Year Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        year: [1970,1971,1972,1973,1974]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install pandas beautifulsoup4 lxml playwright
          playwright install

      - run: |
          YEAR=${{ matrix.year }} python scripts/nfl_rebuild_full_boxscores.py

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/nfl/
          git commit -m "Year ${{ matrix.year }}" || echo "No changes"
          git push
