name: Update NFL Player Files

on:
  workflow_dispatch:

jobs:
  build_players:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run NFL Player Builder
        run: |
          python3 scripts/build_nfl_players.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add docs/data/nfl/players/

          git commit -m "Update NFL player files" || echo "No changes"

          git push
