name: NFL Players Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install unidecode

      - name: Build NFL players
        run: python nfl_players_builder.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add docs/data/nfl/players/
          git add docs/data/nfl/players.json

          git commit -m "Update NFL player files" || echo "No changes"

          git push
