name: Unzip NFL Games

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip games
        run: |
          unzip docs/data/nfl/games.zip -d docs/data/nfl/
          rm docs/data/nfl/games.zip

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/nfl/games
          git commit -m "Unzipped NFL games"
          git push
