name: Unzip AFL Seasons

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip seasons
        run: |
          unzip -o docs/data/afl/afl_seasons.zip -d docs/data/afl/
          rm docs/data/afl/afl_seasons.zip

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/data/afl/*.json
          git commit -m "Extract AFL season JSON files"
          git push
