name: Update NBA Data

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install kaggle pandas

      - name: Configure Kaggle
        run: |
          mkdir ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download dataset
        run: |
          kaggle datasets download -d eoinamoore/historical-nba-data-and-player-box-scores
          unzip historical-nba-data-and-player-box-scores.zip -d data
          ls -R data

      - name: Run builder
        run: python scripts/build_nba_games.py

      - name: Commit files
        run: |
          git config --global user.name "nba-bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Update NBA data" || echo "No changes"
          git push
